### ISSUE TITLE
Foreign key constraint failed on the field: `Order_userId_fkey

### ISSUE THREAD

**Issue by Bishwarup-Das** [joschan21/casecobra#5]
POST /configure/preview?id=clwkitck4000o11hjosmhcdhi 500 in 2300ms
 ⨯ PrismaClientKnownRequestError: 
Invalid `prisma.order.create()` invocation:

Foreign key constraint failed on the field: `Order_userId_fkey (index)`
    at async $$ACTION_0 (./src/app/configure/preview/actions.ts:50:17)
digest: "1520017285"

and also when new user gets registered it doesn't reflects in the user table in the database

**Comment by Rope-a-dope** [comment]
The root cause is because of the schema relation table designed in prisma/schema.prisma.  Please check this out https://www.prisma.io/docs/orm/prisma-schema/data-model/relations. User and Order is one to many relations. The Order model says that the user it related to userId which references [id] in User table.  So we must create User table first to create Order table.  finally figured it out.  Copy the following code from app/api/auth-callback/actions.ts to /preview/actions.ts 
```
  if (!user?.id || !user.email) {
    throw new Error('Invalid user data')
  }

  const existingUser = await db.user.findFirst({
    where: { id: user.id },
  })

  if (!existingUser) {
    await db.user.create({
      data: {
        id: user.id,
        email: user.email,
      },
    })
  }
```

Then remove paypal option, everythin will be fine. I was thinking that the id in user is generated automatically and trying to add userId. But looks like we can create one user with user.id as id. I'm not sure how to better organize the code because it is used twice. Should it be used twice? I think once is good enough. Then how do we deal with the action.ts for auth-callback?

![image](https://github.com/joschan21/casecobra/assets/38259673/4a4accc9-fdce-4ff5-b39d-aa6d2e7c157f)

**Comment by Bishwarup-Das** [comment]
Thanks it was really Helpful

**Comment by Rope-a-dope** [comment]
> Thanks it was really Helpful

Absolutely my pleasure
